spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAIVxkBPY2GGqcG
      secret-key: D9JsFtRTAiELo5Lm1ZIyaJfzF5yCJp
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hanlong

  application:
    name: gulimall-third-party

server:
  port: 30000
